### ISSUE TITLE
Reiseberichte

### ISSUE THREAD

**Issue by therborn** [fherborn/kar-theme#11]
Soll von den Reiseberichten nichts auf der Startseite erscheinen? Auch in der Sidebar werden die nicht angezeigt. Wäre es nicht besser, wenn da ebenfalls kleine Beiträge sind, ich schreib ja nicht jeden Tag, dazu gibt es die Podcasts und auch mal allgemeine Beiträge. Wird also nicht so arg überladen. Oder seh ich das falsch?

**Comment by fherborn** [comment]
Doch steht auf dem Plan
