### ISSUE TITLE
Podcast Folgen 

### ISSUE THREAD

**Issue by therborn** [fherborn/kar-theme#13]
Abstand zwischen Abspielfeld und Fotos im Post bitte überprüfen.

**Comment by therborn** [comment]
Jetzt steht der Text unter dem Abspielfeld. Andersrum wäre schöner, dann liest man erst die Beschreibung und spielt dann ab....

**Comment by fherborn** [comment]
@therborn Bitte nach Update nochmal überprüfen und falls es noch da ist das Issue wieder öffnen
