### ISSUE TITLE
Map Reiselinien

### ISSUE THREAD

**Issue by therborn** [fherborn/kar-theme#17]
Ist es evtl. möglich die Reiseroute in einer anderen Farbe darzustellen? Vielleicht in meinem Lieblingsgrün? ;-) Denn in der Karte sind die Straßen ebenfalls in orange dargestellt.....

**Comment by fherborn** [comment]
Kann ich machen. Dann schreib mal die Farbe (#....) von dem grün hier rein.

**Comment by therborn** [comment]
HP #5baf07

**Comment by fherborn** [comment]
Im Moment wird übrigens die Secondary Color verwendet. Die taucht überall immer mal wieder auf. Soll dann alles was jetzt Orange ist grün werden?

**Comment by therborn** [comment]
die Markierungspunkte und die Reiselinien, ja
