### ISSUE TITLE
Galeriedarstellung

### ISSUE THREAD

**Issue by therborn** [fherborn/kar-theme#23]
Bei der Darstellung von Materials, Größe und Style wird nicht zwischen Tatjana´s Kunst und Detlef´s Kunst unterschieden. Wird eine dieser Parameter als Auswahl angeklickt, erscheinen die Bilder aus beiden Galerien. Ist da so gewollt? Wäre es nicht besser, wenn auch dort die Bilder getrennt voneinander werden?

**Comment by fherborn** [comment]
1. Ja so gewollt. 2. Technisch schwierig machbar
